name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar diretório para artefatos
        run: mkdir testArtifacts

      # Configuração do ambiente
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Newman e Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Executar testes
        run: newman run ServeRest.postman_collection.json -e serveRest_env.postman_environment.json -r cli,htmlextra

      - name: Salvar relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: newman
