name: Newman Run
#
on:
  schedule:
    - cron: "0 14 * * *"
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Create directory for storing test artifacts
      - name: Create dir
        run: |
          mkdir testArtifacts

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1  # Ou a versão que você utiliza localmente


      # Step 4: Install Newman and Newman Reporter
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Step 5: Run the tests using Newman
      - name: Run Test
        run: newman run Serverrest.postman_collection.json -e ServeRest.postman_environment.json -r cli,htmlextra

      # Step 6: Upload test report as artifact
      - name: Report
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: newman
